import type { Client } from "@libsql/client";
import { createTursoClient } from "../db/client";
import { getPushSubscriptions } from "../db/repositories/push";
import { createWebPushSender } from "../push/webpush";
import type { PushPayload } from "../push/types";

const VERSION="3.0-established-microcap";
const MIN_CAP=8_000_000,MAX_CAP=300_000_000,MIN_VOL=2_000_000,MIN_VOL_CAP=0.08,MIN_HISTORY_DAYS=7;
const MIN_24H=3,MAX_24H=35,MIN_7D=-10,MAX_SPREAD_PCT=0.75,MIN_CONFIRM_ROI=2;
const CG_PAGES=[2,3] as const;

type CG={id:string;symbol:string;name:string;current_price:number;market_cap:number;total_volume:number;price_change_percentage_1h_in_currency?:number;price_change_percentage_24h_in_currency?:number;price_change_percentage_7d_in_currency?:number;ath_date?:string;atl_date?:string};
type Binance24={symbol:string;quoteVolume:string;lastPrice:string};
type Book={symbol:string;bidPrice:string;askPrice:string};
type Active={id:number;coinGeckoId:string;symbol:string;name:string;binanceSymbol:string;entryPrice:number;entryAt:number};

async function json(url:string){const r=await fetch(url,{headers:{accept:"application/json","user-agent":"moonshot-radar/3.0"},signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return r.json();}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null;}
function oldestMarketDate(c:CG){const ds=[c.ath_date,c.atl_date].map(x=>x?Date.parse(x):NaN).filter(Number.isFinite);return ds.length?Math.min(...ds):null;}
function spreadPct(b?:Book){if(!b)return null;const bid=n(b.bidPrice),ask=n(b.askPrice);if(!bid||!ask||bid<=0||ask<=0)return null;return((ask-bid)/((ask+bid)/2))*100;}

async function ensure(c:Client){await c.batch([
`DROP TABLE IF EXISTS solana_validated_push_deliveries`,`DROP TABLE IF EXISTS solana_validated_decisions`,`DROP TABLE IF EXISTS solana_validated_snapshots`,`DROP TABLE IF EXISTS solana_validated_cases`,
`CREATE TABLE IF NOT EXISTS microcap_cases(id INTEGER PRIMARY KEY AUTOINCREMENT,coingecko_id TEXT NOT NULL UNIQUE,symbol TEXT NOT NULL,name TEXT NOT NULL,binance_symbol TEXT NOT NULL,entry_at INTEGER NOT NULL,entry_price REAL NOT NULL,market_cap_usd REAL NOT NULL,volume_24h_usd REAL NOT NULL,volume_cap_ratio REAL NOT NULL,change_1h_pct REAL,change_24h_pct REAL,change_7d_pct REAL,status TEXT NOT NULL DEFAULT 'ACTIVE',radar_version TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS microcap_snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL REFERENCES microcap_cases(id) ON DELETE CASCADE,stage TEXT NOT NULL,captured_at INTEGER NOT NULL,price REAL NOT NULL,quote_volume_24h_usd REAL,spread_pct REAL,UNIQUE(case_id,stage))`,
`CREATE TABLE IF NOT EXISTS microcap_decisions(case_id INTEGER PRIMARY KEY REFERENCES microcap_cases(id) ON DELETE CASCADE,decided_at INTEGER NOT NULL,status TEXT NOT NULL,reject_reason TEXT,confirm_roi_pct REAL,spread_pct REAL,quote_volume_24h_usd REAL,radar_version TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS microcap_push_deliveries(case_id INTEGER PRIMARY KEY REFERENCES microcap_cases(id) ON DELETE CASCADE,sent_at INTEGER NOT NULL)`],"write");}

async function marketUniverse(){const all:CG[]=[];for(const p of CG_PAGES){const q=new URL("https://api.coingecko.com/api/v3/coins/markets");q.searchParams.set("vs_currency","usd");q.searchParams.set("order","market_cap_desc");q.searchParams.set("per_page","250");q.searchParams.set("page",String(p));q.searchParams.set("sparkline","false");q.searchParams.set("price_change_percentage","1h,24h,7d");all.push(...await json(q.toString()));}return all;}
async function binance(){const [ex,tickers,books]=await Promise.all([json("https://api.binance.com/api/v3/exchangeInfo"),json("https://api.binance.com/api/v3/ticker/24hr"),json("https://api.binance.com/api/v3/ticker/bookTicker")]);const tradable=new Set<string>((ex.symbols??[]).filter((s:any)=>s.status==="TRADING"&&s.quoteAsset==="USDT"&&s.isSpotTradingAllowed!==false).map((s:any)=>s.symbol));const t=new Map<string,Binance24>((tickers as Binance24[]).map(x=>[x.symbol,x]));const b=new Map<string,Book>((books as Book[]).map(x=>[x.symbol,x]));return{tradable,t,b};}
function admission(c:CG,b:any,now:number){const sym=`${c.symbol.toUpperCase()}USDT`;const cap=n(c.market_cap),vol=n(c.total_volume),p=n(c.current_price),h1=n(c.price_change_percentage_1h_in_currency)??0,h24=n(c.price_change_percentage_24h_in_currency)??0,d7=n(c.price_change_percentage_7d_in_currency)??0;const oldest=oldestMarketDate(c);if(!b.tradable.has(sym)||!cap||!vol||!p||!oldest)return null;const days=(now-oldest)/86_400_000;if(days<MIN_HISTORY_DAYS||cap<MIN_CAP||cap>MAX_CAP||vol<MIN_VOL||vol/cap<MIN_VOL_CAP||h24<MIN_24H||h24>MAX_24H||d7<MIN_7D)return null;const ticker=b.t.get(sym);const quote=n(ticker?.quoteVolume);const last=n(ticker?.lastPrice);const spread=spreadPct(b.b.get(sym));if(!quote||quote<MIN_VOL||!last||spread==null||spread>MAX_SPREAD_PCT)return null;return{sym,cap,vol,p:last,h1,h24,d7,ratio:vol/cap,quote,spread};}
async function addCandidates(c:Client,now:number,u:CG[],b:any){let added=0;for(const coin of u){const a=admission(coin,b,now);if(!a)continue;const r=await c.execute({sql:`INSERT INTO microcap_cases(coingecko_id,symbol,name,binance_symbol,entry_at,entry_price,market_cap_usd,volume_24h_usd,volume_cap_ratio,change_1h_pct,change_24h_pct,change_7d_pct,status,radar_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'ACTIVE',?) ON CONFLICT DO NOTHING RETURNING id`,args:[coin.id,coin.symbol.toUpperCase(),coin.name,a.sym,now,a.p,a.cap,a.vol,a.ratio,a.h1,a.h24,a.d7,VERSION]});if(r.rows.length){const id=Number(r.rows[0].id);await c.execute({sql:`INSERT INTO microcap_snapshots(case_id,stage,captured_at,price,quote_volume_24h_usd,spread_pct) VALUES(?, 'INITIAL', ?, ?, ?, ?)`,args:[id,now,a.p,a.quote,a.spread]});added++;}}return added;}
async function active(c:Client){const r=await c.execute(`SELECT id,coingecko_id,symbol,name,binance_symbol,entry_price,entry_at FROM microcap_cases WHERE status='ACTIVE' ORDER BY entry_at ASC LIMIT 50`);return r.rows.map(x=>({id:Number(x.id),coinGeckoId:String(x.coingecko_id),symbol:String(x.symbol),name:String(x.name),binanceSymbol:String(x.binance_symbol),entryPrice:Number(x.entry_price),entryAt:Number(x.entry_at)}));}
async function progress(c:Client,rows:Active[],b:any,now:number){let decisions=0,passes=0,pushes=0;for(const row of rows){const ticker=b.t.get(row.binanceSymbol);const price=n(ticker?.lastPrice),quote=n(ticker?.quoteVolume),spread=spreadPct(b.b.get(row.binanceSymbol));if(!price||!quote||spread==null)continue;const age=(now-row.entryAt)/60000;for(const [stage,due] of [["PLUS_15",15],["PLUS_30",30],["PLUS_60",60],["PLUS_180",180]] as const){if(age>=due)await c.execute({sql:`INSERT OR IGNORE INTO microcap_snapshots(case_id,stage,captured_at,price,quote_volume_24h_usd,spread_pct) VALUES(?,?,?,?,?,?)`,args:[row.id,stage,now,price,quote,spread]});}
if(age>=15){const ex=await c.execute({sql:"SELECT 1 FROM microcap_decisions WHERE case_id=?",args:[row.id]});if(!ex.rows.length){const roi=(price/row.entryPrice-1)*100;let status="PASS",reason:string|null=null;if(roi<MIN_CONFIRM_ROI){status="REJECT";reason="CONFIRM_ROI_BELOW_2PCT";}else if(spread>MAX_SPREAD_PCT){status="REJECT";reason="SPREAD_TOO_WIDE";}else if(quote<MIN_VOL){status="REJECT";reason="QUOTE_VOLUME_TOO_LOW";}await c.execute({sql:`INSERT INTO microcap_decisions(case_id,decided_at,status,reject_reason,confirm_roi_pct,spread_pct,quote_volume_24h_usd,radar_version) VALUES(?,?,?,?,?,?,?,?)`,args:[row.id,now,status,reason,roi,spread,quote,VERSION]});decisions++;if(status==="PASS"){passes++;const claim=await c.execute({sql:"INSERT OR IGNORE INTO microcap_push_deliveries(case_id,sent_at) VALUES(?,?)",args:[row.id,now]});if(claim.rowsAffected){const send=createWebPushSender({getSubscriptions:()=>getPushSubscriptions(c)});const payload:PushPayload={title:"🚀 Micro-Cap Radar · Confirmed",body:`${row.symbol} | +15 ${roi.toFixed(1)}% | spread ${spread.toFixed(2)}%`,url:`/radar`,mint:row.binanceSymbol,decisionId:row.id,tokenCaseId:row.id,decisionStatus:"PASS",decisionStage:"PLUS_10",plus10RoiPct:roi,momentum5To10Pct:null,symbol:row.symbol};try{await send(payload);pushes++;}catch(e){console.warn("[microcap] push failed",e instanceof Error?e.message:String(e));}}}}}
if(age>=180)await c.execute({sql:"UPDATE microcap_cases SET status='CLOSED' WHERE id=?",args:[row.id]});}return{decisions,passes,pushes};}

export async function runMicrocapRadar(){const c=await createTursoClient();const now=Date.now();try{await ensure(c);const [u,b]=await Promise.all([marketUniverse(),binance()]);const added=await addCandidates(c,now,u,b);const a=await active(c);const p=await progress(c,a,b,now);const counts=await c.execute(`SELECT COUNT(*) total,SUM(CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) active FROM microcap_cases`);const summary={mode:"ESTABLISHED_MICROCAP",version:VERSION,universe:u.length,candidatesAdded:added,activeScanned:a.length,decisionsCreated:p.decisions,passesCreated:p.passes,pushesSent:p.pushes,totals:{cases:Number(counts.rows[0]?.total??0),active:Number(counts.rows[0]?.active??0)},gates:{marketCap:[MIN_CAP,MAX_CAP],minVolume24h:MIN_VOL,minVolumeCapRatio:MIN_VOL_CAP,minHistoryDays:MIN_HISTORY_DAYS,price24h:[MIN_24H,MAX_24H],min7d:MIN_7D,maxSpreadPct:MAX_SPREAD_PCT,minConfirmRoiPct:MIN_CONFIRM_ROI}};console.info("[microcap] cron finished",summary);return summary;}finally{c.close();}}
