import type { Client } from "@libsql/client";
import { createTursoClient } from "../db/client";
import { getPushSubscriptions } from "../db/repositories/push";
import { createWebPushSender } from "../push/webpush";
import type { PushPayload } from "../push/types";

const VERSION="3.0-established-microcap-coinbase";
const MIN_CAP=8_000_000,MAX_CAP=300_000_000,MIN_VOL=2_000_000,MIN_VOL_CAP=0.08,MIN_HISTORY_DAYS=7;
const MIN_24H=3,MAX_24H=35,MIN_7D=-10,MAX_SPREAD_PCT=0.75,MIN_CONFIRM_ROI=2;
const CG_PAGES=[2,3] as const;
const MAX_ADMISSION_CHECKS=20;

type CG={id:string;symbol:string;name:string;current_price:number;market_cap:number;total_volume:number;price_change_percentage_1h_in_currency?:number;price_change_percentage_24h_in_currency?:number;price_change_percentage_7d_in_currency?:number;ath_date?:string;atl_date?:string};
type CoinbaseProduct={id:string;base_currency:string;quote_currency:string;status:string;trading_disabled?:boolean;cancel_only?:boolean};
type CoinbaseTicker={price:string;bid:string;ask:string;volume:string};
type Active={id:number;coinGeckoId:string;symbol:string;name:string;venueSymbol:string;entryPrice:number;entryAt:number};

async function json(url:string){const r=await fetch(url,{headers:{accept:"application/json","user-agent":"moonshot-radar/3.0"},signal:AbortSignal.timeout(10_000)});if(!r.ok)throw new Error(`${new URL(url).hostname} ${r.status}`);return r.json();}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:null;}
function oldestMarketDate(c:CG){const ds=[c.ath_date,c.atl_date].map(x=>x?Date.parse(x):NaN).filter(Number.isFinite);return ds.length?Math.min(...ds):null;}
function tickerMetrics(t:CoinbaseTicker){const price=n(t.price),bid=n(t.bid),ask=n(t.ask),baseVol=n(t.volume);if(!price||!bid||!ask||!baseVol||price<=0||bid<=0||ask<=0)return null;return{price,bid,ask,quote:baseVol*price,spread:((ask-bid)/((ask+bid)/2))*100};}

async function ensure(c:Client){
  const info=await c.execute("PRAGMA table_info(microcap_cases)");
  if(info.rows.some(r=>String(r.name)==="binance_symbol")&&!info.rows.some(r=>String(r.name)==="venue_symbol"))await c.execute("ALTER TABLE microcap_cases RENAME COLUMN binance_symbol TO venue_symbol");
  await c.batch([
    `DROP TABLE IF EXISTS solana_validated_push_deliveries`,`DROP TABLE IF EXISTS solana_validated_decisions`,`DROP TABLE IF EXISTS solana_validated_snapshots`,`DROP TABLE IF EXISTS solana_validated_cases`,
    `CREATE TABLE IF NOT EXISTS microcap_cases(id INTEGER PRIMARY KEY AUTOINCREMENT,coingecko_id TEXT NOT NULL UNIQUE,symbol TEXT NOT NULL,name TEXT NOT NULL,venue_symbol TEXT NOT NULL,entry_at INTEGER NOT NULL,entry_price REAL NOT NULL,market_cap_usd REAL NOT NULL,volume_24h_usd REAL NOT NULL,volume_cap_ratio REAL NOT NULL,change_1h_pct REAL,change_24h_pct REAL,change_7d_pct REAL,status TEXT NOT NULL DEFAULT 'ACTIVE',radar_version TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS microcap_snapshots(id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL REFERENCES microcap_cases(id) ON DELETE CASCADE,stage TEXT NOT NULL,captured_at INTEGER NOT NULL,price REAL NOT NULL,quote_volume_24h_usd REAL,spread_pct REAL,UNIQUE(case_id,stage))`,
    `CREATE TABLE IF NOT EXISTS microcap_decisions(case_id INTEGER PRIMARY KEY REFERENCES microcap_cases(id) ON DELETE CASCADE,decided_at INTEGER NOT NULL,status TEXT NOT NULL,reject_reason TEXT,confirm_roi_pct REAL,spread_pct REAL,quote_volume_24h_usd REAL,radar_version TEXT NOT NULL)`,
    `CREATE TABLE IF NOT EXISTS microcap_push_deliveries(case_id INTEGER PRIMARY KEY REFERENCES microcap_cases(id) ON DELETE CASCADE,sent_at INTEGER NOT NULL)`],"write");
}

async function marketUniverse(){const all:CG[]=[];for(const p of CG_PAGES){const q=new URL("https://api.coingecko.com/api/v3/coins/markets");q.searchParams.set("vs_currency","usd");q.searchParams.set("order","market_cap_desc");q.searchParams.set("per_page","250");q.searchParams.set("page",String(p));q.searchParams.set("sparkline","false");q.searchParams.set("price_change_percentage","1h,24h,7d");all.push(...await json(q.toString()));}return all;}
async function coinbaseProducts(){const rows=await json("https://api.exchange.coinbase.com/products") as CoinbaseProduct[];return rows.filter(p=>p.status==="online"&&!p.trading_disabled&&!p.cancel_only&&(p.quote_currency==="USD"||p.quote_currency==="USDC"));}
async function ticker(product:string){return await json(`https://api.exchange.coinbase.com/products/${encodeURIComponent(product)}/ticker`) as CoinbaseTicker;}
function coarse(c:CG,now:number){const cap=n(c.market_cap),vol=n(c.total_volume),p=n(c.current_price),h1=n(c.price_change_percentage_1h_in_currency)??0,h24=n(c.price_change_percentage_24h_in_currency)??0,d7=n(c.price_change_percentage_7d_in_currency)??0,oldest=oldestMarketDate(c);if(!cap||!vol||!p||!oldest)return null;const days=(now-oldest)/86_400_000;if(days<MIN_HISTORY_DAYS||cap<MIN_CAP||cap>MAX_CAP||vol<MIN_VOL||vol/cap<MIN_VOL_CAP||h24<MIN_24H||h24>MAX_24H||d7<MIN_7D)return null;return{cap,vol,h1,h24,d7,ratio:vol/cap};}
async function addCandidates(c:Client,now:number,u:CG[],products:CoinbaseProduct[]){const byBase=new Map<string,CoinbaseProduct[]>();for(const p of products){const a=byBase.get(p.base_currency)??[];a.push(p);byBase.set(p.base_currency,a);}const prelim=u.map(coin=>({coin,a:coarse(coin,now)})).filter((x):x is {coin:CG;a:NonNullable<ReturnType<typeof coarse>>}=>x.a!=null&&byBase.has(x.coin.symbol.toUpperCase())).sort((x,y)=>(y.a.ratio-x.a.ratio)||(y.a.h24-x.a.h24)).slice(0,MAX_ADMISSION_CHECKS);let added=0,venueChecked=0;for(const {coin,a} of prelim){const options=byBase.get(coin.symbol.toUpperCase())??[];let chosen:CoinbaseProduct|null=null,tm:ReturnType<typeof tickerMetrics>|null=null;for(const p of options){try{const m=tickerMetrics(await ticker(p.id));venueChecked++;if(m&&m.quote>=MIN_VOL&&m.spread<=MAX_SPREAD_PCT){chosen=p;tm=m;break;}}catch{continue;}}if(!chosen||!tm)continue;const r=await c.execute({sql:`INSERT INTO microcap_cases(coingecko_id,symbol,name,venue_symbol,entry_at,entry_price,market_cap_usd,volume_24h_usd,volume_cap_ratio,change_1h_pct,change_24h_pct,change_7d_pct,status,radar_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'ACTIVE',?) ON CONFLICT DO NOTHING RETURNING id`,args:[coin.id,coin.symbol.toUpperCase(),coin.name,chosen.id,now,tm.price,a.cap,a.vol,a.ratio,a.h1,a.h24,a.d7,VERSION]});if(r.rows.length){const id=Number(r.rows[0].id);await c.execute({sql:`INSERT INTO microcap_snapshots(case_id,stage,captured_at,price,quote_volume_24h_usd,spread_pct) VALUES(?, 'INITIAL', ?, ?, ?, ?)`,args:[id,now,tm.price,tm.quote,tm.spread]});added++;}}return{added,venueChecked,prelim:prelim.length};}
async function active(c:Client){const r=await c.execute(`SELECT id,coingecko_id,symbol,name,venue_symbol,entry_price,entry_at FROM microcap_cases WHERE status='ACTIVE' ORDER BY entry_at ASC LIMIT 50`);return r.rows.map(x=>({id:Number(x.id),coinGeckoId:String(x.coingecko_id),symbol:String(x.symbol),name:String(x.name),venueSymbol:String(x.venue_symbol),entryPrice:Number(x.entry_price),entryAt:Number(x.entry_at)}));}
async function progress(c:Client,rows:Active[],now:number){let decisions=0,passes=0,pushes=0;for(const row of rows){let tm:ReturnType<typeof tickerMetrics>|null=null;try{tm=tickerMetrics(await ticker(row.venueSymbol));}catch{continue;}if(!tm)continue;const age=(now-row.entryAt)/60000;for(const [stage,due] of [["PLUS_15",15],["PLUS_30",30],["PLUS_60",60],["PLUS_180",180]] as const){if(age>=due)await c.execute({sql:`INSERT OR IGNORE INTO microcap_snapshots(case_id,stage,captured_at,price,quote_volume_24h_usd,spread_pct) VALUES(?,?,?,?,?,?)`,args:[row.id,stage,now,tm.price,tm.quote,tm.spread]});}
if(age>=15){const ex=await c.execute({sql:"SELECT 1 FROM microcap_decisions WHERE case_id=?",args:[row.id]});if(!ex.rows.length){const roi=(tm.price/row.entryPrice-1)*100;let status="PASS",reason:string|null=null;if(roi<MIN_CONFIRM_ROI){status="REJECT";reason="CONFIRM_ROI_BELOW_2PCT";}else if(tm.spread>MAX_SPREAD_PCT){status="REJECT";reason="SPREAD_TOO_WIDE";}else if(tm.quote<MIN_VOL){status="REJECT";reason="QUOTE_VOLUME_TOO_LOW";}await c.execute({sql:`INSERT INTO microcap_decisions(case_id,decided_at,status,reject_reason,confirm_roi_pct,spread_pct,quote_volume_24h_usd,radar_version) VALUES(?,?,?,?,?,?,?,?)`,args:[row.id,now,status,reason,roi,tm.spread,tm.quote,VERSION]});decisions++;if(status==="PASS"){passes++;const claim=await c.execute({sql:"INSERT OR IGNORE INTO microcap_push_deliveries(case_id,sent_at) VALUES(?,?)",args:[row.id,now]});if(claim.rowsAffected){const send=createWebPushSender({getSubscriptions:()=>getPushSubscriptions(c)});const payload:PushPayload={title:"🚀 Micro-Cap Radar · Confirmed",body:`${row.symbol} | +15 ${roi.toFixed(1)}% | Coinbase spread ${tm.spread.toFixed(2)}%`,url:"/radar",mint:row.venueSymbol,decisionId:row.id,tokenCaseId:row.id,decisionStatus:"PASS",decisionStage:"PLUS_10",plus10RoiPct:roi,momentum5To10Pct:null,symbol:row.symbol};try{await send(payload);pushes++;}catch(e){console.warn("[microcap] push failed",e instanceof Error?e.message:String(e));}}}}}
if(age>=180)await c.execute({sql:"UPDATE microcap_cases SET status='CLOSED' WHERE id=?",args:[row.id]});}return{decisions,passes,pushes};}

export async function runMicrocapRadar(){const c=await createTursoClient();const now=Date.now();try{await ensure(c);const [u,products]=await Promise.all([marketUniverse(),coinbaseProducts()]);const admission=await addCandidates(c,now,u,products);const a=await active(c);const p=await progress(c,a,now);const counts=await c.execute(`SELECT COUNT(*) total,SUM(CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) active FROM microcap_cases`);const summary={mode:"ESTABLISHED_MICROCAP",venue:"Coinbase Exchange",version:VERSION,universe:u.length,preliminaryCandidates:admission.prelim,venueChecks:admission.venueChecked,candidatesAdded:admission.added,activeScanned:a.length,decisionsCreated:p.decisions,passesCreated:p.passes,pushesSent:p.pushes,totals:{cases:Number(counts.rows[0]?.total??0),active:Number(counts.rows[0]?.active??0)},gates:{marketCap:[MIN_CAP,MAX_CAP],minVolume24h:MIN_VOL,minVolumeCapRatio:MIN_VOL_CAP,minHistoryDays:MIN_HISTORY_DAYS,price24h:[MIN_24H,MAX_24H],min7d:MIN_7D,maxSpreadPct:MAX_SPREAD_PCT,minConfirmRoiPct:MIN_CONFIRM_ROI}};console.info("[microcap] cron finished",summary);return summary;}finally{c.close();}}
