import type { Client, Row } from "@libsql/client";
import { createTursoClient } from "../db/client";
import { getPushSubscriptions } from "../db/repositories/push";
import { evaluateRadar24 } from "../decisions/engine";
import { validateJupiterExecution } from "../push/executionGate";
import { createWebPushSender } from "../push/webpush";
import type { PushPayload } from "../push/types";

const NETWORK = "solana";
const RADAR_VERSION = "2.4-solana-post-validation";
const MIN_VALIDATION_AGE_MS = 15 * 60_000;
const MAX_VALIDATION_AGE_MS = 60 * 60_000;
const MIN_ENTRY_LIQUIDITY_USD = 25_000;
const MAX_NEW_CANDIDATES_PER_RUN = 10;
const MAX_DUE_VALIDATIONS_PER_RUN = 10;
const MAX_ACTIVE_PER_RUN = 10;
const MAX_DUE_BACKLOG = 30;
const MAX_ROUND_TRIP_LOSS_PCT = 3;
const DISCOVERY_PAGES = [1] as const;
const GECKO_REQUEST_GAP_MS = 1_500;
const GECKO_TIMEOUT_MS = 8_000;
const STAGES = [["PLUS_5",5],["PLUS_10",10],["PLUS_15",15],["PLUS_30",30],["PLUS_60",60]] as const;
const SOL_MINT = "So11111111111111111111111111111111111111112";
const USDC_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const USDT_MINT = "Es9vMFrzaCERmJfrF4H2FYD7hJcUAPXnY8W3K2p5uX3";
const MAJOR_MINTS = new Set([SOL_MINT, USDC_MINT, USDT_MINT]);

type Pool={poolAddress:string;mint:string;symbol:string|null;createdAt:number;price:number;liquidityUsd:number|null;volumeH1Usd:number|null;buysH1:number;sellsH1:number};
type CaseRow={id:number;poolAddress:string;mint:string;symbol:string|null;poolCreatedAt:number;firstSeenAt:number;entryPrice:number;entryLiquidityUsd:number;status:string};
type RunError={caseId:number|null;message:string};

class GeckoRateLimitError extends Error{constructor(){super("GeckoTerminal 429 rate limit");this.name="GeckoRateLimitError";}}

function sleep(ms:number){return new Promise(resolve=>setTimeout(resolve,ms));}
function asNumber(v:unknown):number|null{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:null;}
function relationAddress(r:any,key:"base_token"|"quote_token"){const id=r?.relationships?.[key]?.data?.id;return typeof id==="string"?id.replace(/^solana_/,""):null;}
function parsePool(r:any):Pool|null{const a=r?.attributes??{};const base=relationAddress(r,"base_token");const quote=relationAddress(r,"quote_token");if(!base||!quote)return null;const targetIsQuote=MAJOR_MINTS.has(base)&&!MAJOR_MINTS.has(quote);const mint=targetIsQuote?quote:base;if(MAJOR_MINTS.has(mint))return null;const price=asNumber(targetIsQuote?a.quote_token_price_usd:a.base_token_price_usd);const createdAt=Date.parse(String(a.pool_created_at??""));const poolAddress=typeof a.address==="string"?a.address:String(r?.id??"").replace(/^solana_/,"");if(!poolAddress||!Number.isFinite(createdAt)||price==null||price<=0)return null;const tx=a.transactions?.h1??{};const parts=typeof a.name==="string"?a.name.split("/").map((x:string)=>x.trim()):[];return{poolAddress,mint,symbol:targetIsQuote?(parts[1]??null):(parts[0]??null),createdAt,price,liquidityUsd:asNumber(a.reserve_in_usd),volumeH1Usd:asNumber(a.volume_usd?.h1),buysH1:Math.max(0,Number(tx.buys??0)||0),sellsH1:Math.max(0,Number(tx.sells??0)||0)};}
async function getJson(url:string){const r=await fetch(url,{headers:{accept:"application/json","user-agent":"radar-v24/2.4 validated"},signal:AbortSignal.timeout(GECKO_TIMEOUT_MS)});if(r.status===429)throw new GeckoRateLimitError();if(!r.ok)throw new Error(`GeckoTerminal ${r.status} for ${url}`);return r.json();}
async function discoverFresh():Promise<Pool[]>{const pages:any[]=[];for(const page of DISCOVERY_PAGES){if(pages.length)await sleep(GECKO_REQUEST_GAP_MS);pages.push(await getJson(`https://api.geckoterminal.com/api/v2/networks/${NETWORK}/new_pools?page=${page}`));}const all=pages.flatMap(j=>Array.isArray(j?.data)?j.data:[]).map(parsePool).filter((p:Pool|null):p is Pool=>p!=null);const best=new Map<string,Pool>();for(const p of all){const cur=best.get(p.mint);if(!cur||(p.liquidityUsd??0)>(cur.liquidityUsd??0))best.set(p.mint,p);}return[...best.values()];}
async function fetchPools(addresses:string[]):Promise<Map<string,Pool>>{if(!addresses.length)return new Map();const j=await getJson(`https://api.geckoterminal.com/api/v2/networks/${NETWORK}/pools/multi/${addresses.map(encodeURIComponent).join(",")}`);const pools:Pool[]=Array.isArray(j?.data)?j.data.map(parsePool).filter((p:Pool|null):p is Pool=>p!=null):[];return new Map(pools.map(p=>[p.poolAddress.toLowerCase(),p]));}

async function ensureSchema(c:Client){await c.batch([
`CREATE TABLE IF NOT EXISTS solana_validated_cases (id INTEGER PRIMARY KEY AUTOINCREMENT,pool_address TEXT NOT NULL UNIQUE,mint TEXT NOT NULL UNIQUE,symbol TEXT,pool_created_at INTEGER,validated_at INTEGER,first_seen_at INTEGER NOT NULL,entry_price REAL NOT NULL,entry_liquidity_usd REAL NOT NULL,entry_volume_h1_usd REAL,entry_buys_h1 INTEGER NOT NULL,entry_sells_h1 INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'WAITING',validation_reason TEXT)`,
`CREATE TABLE IF NOT EXISTS solana_validated_snapshots (id INTEGER PRIMARY KEY AUTOINCREMENT,case_id INTEGER NOT NULL REFERENCES solana_validated_cases(id) ON DELETE CASCADE,stage TEXT NOT NULL,captured_at INTEGER NOT NULL,price REAL NOT NULL,liquidity_usd REAL,UNIQUE(case_id,stage))`,
`CREATE TABLE IF NOT EXISTS solana_validated_decisions (case_id INTEGER PRIMARY KEY REFERENCES solana_validated_cases(id) ON DELETE CASCADE,decided_at INTEGER NOT NULL,status TEXT NOT NULL,reject_reason TEXT,plus5_roi_pct REAL,plus10_roi_pct REAL,momentum_5_to_10_pct REAL,plus10_liquidity_usd REAL,execution_status TEXT,round_trip_loss_pct REAL,radar_version TEXT NOT NULL)`,
`CREATE TABLE IF NOT EXISTS solana_validated_push_deliveries (case_id INTEGER PRIMARY KEY REFERENCES solana_validated_cases(id) ON DELETE CASCADE,sent_at INTEGER NOT NULL)`],"write");}

async function cleanupDatabase(c:Client,now:number){
  const expired=await c.execute({sql:"DELETE FROM solana_validated_cases WHERE status='WAITING' AND pool_created_at IS NOT NULL AND pool_created_at < ?",args:[now-MAX_VALIDATION_AGE_MS]});
  const oldClosed=await c.execute("DELETE FROM solana_validated_cases WHERE status='CLOSED' AND id NOT IN (SELECT case_id FROM solana_validated_decisions)");
  const dueCutoff=now-MIN_VALIDATION_AGE_MS;
  const trim=await c.execute({sql:`DELETE FROM solana_validated_cases WHERE status='WAITING' AND pool_created_at <= ? AND id NOT IN (SELECT id FROM solana_validated_cases WHERE status='WAITING' AND pool_created_at <= ? ORDER BY entry_liquidity_usd DESC, COALESCE(entry_volume_h1_usd,0) DESC LIMIT ${MAX_DUE_BACKLOG})`,args:[dueCutoff,dueCutoff]});
  return{expiredWaitingDeleted:expired.rowsAffected,closedWithoutDecisionDeleted:oldClosed.rowsAffected,backlogDeleted:trim.rowsAffected};
}

async function collectWaiting(c:Client,now:number){const pools=(await discoverFresh()).filter(p=>now-p.createdAt>=0&&now-p.createdAt<MIN_VALIDATION_AGE_MS).sort((a,b)=>((b.liquidityUsd??0)-(a.liquidityUsd??0))||((b.volumeH1Usd??0)-(a.volumeH1Usd??0)));let added=0;for(const p of pools.slice(0,MAX_NEW_CANDIDATES_PER_RUN)){const r=await c.execute({sql:`INSERT INTO solana_validated_cases(pool_address,mint,symbol,pool_created_at,first_seen_at,entry_price,entry_liquidity_usd,entry_volume_h1_usd,entry_buys_h1,entry_sells_h1,status) VALUES(?,?,?,?,?,?,?,?,?,?, 'WAITING') ON CONFLICT DO NOTHING RETURNING id`,args:[p.poolAddress,p.mint,p.symbol,p.createdAt,now,p.price,p.liquidityUsd??0,p.volumeH1Usd,p.buysH1,p.sellsH1]});if(r.rows.length)added++;}return{discovered:pools.length,waitingAdded:added};}
function mapCase(r:Row):CaseRow{return{id:Number(r.id),poolAddress:String(r.pool_address),mint:String(r.mint),symbol:r.symbol==null?null:String(r.symbol),poolCreatedAt:Number(r.pool_created_at??0),firstSeenAt:Number(r.first_seen_at),entryPrice:Number(r.entry_price),entryLiquidityUsd:Number(r.entry_liquidity_usd),status:String(r.status)};}
async function listDueWaiting(c:Client,now:number){const r=await c.execute({sql:`SELECT * FROM solana_validated_cases WHERE status='WAITING' AND pool_created_at<=? AND pool_created_at>=? ORDER BY entry_liquidity_usd DESC, COALESCE(entry_volume_h1_usd,0) DESC LIMIT ${MAX_DUE_VALIDATIONS_PER_RUN}`,args:[now-MIN_VALIDATION_AGE_MS,now-MAX_VALIDATION_AGE_MS]});return r.rows.map(mapCase);}
async function listActive(c:Client){const r=await c.execute(`SELECT * FROM solana_validated_cases WHERE status='ACTIVE' ORDER BY first_seen_at ASC LIMIT ${MAX_ACTIVE_PER_RUN}`);return r.rows.map(mapCase);}
function validationPass(p:Pool){return p.liquidityUsd!=null&&p.liquidityUsd>=MIN_ENTRY_LIQUIDITY_USD&&(p.volumeH1Usd??0)>0&&(p.buysH1+p.sellsH1)>0;}
async function validateWaiting(c:Client,now:number){const due=await listDueWaiting(c,now);if(!due.length)return{activated:0,invalidDeleted:0,validationDue:0};const pools=await fetchPools(due.map(r=>r.poolAddress));let activated=0,invalidDeleted=0;for(const row of due){const p=pools.get(row.poolAddress.toLowerCase());if(!p||!validationPass(p)){await c.execute({sql:"DELETE FROM solana_validated_cases WHERE id=?",args:[row.id]});invalidDeleted++;continue;}await c.execute({sql:`UPDATE solana_validated_cases SET status='ACTIVE',validated_at=?,first_seen_at=?,entry_price=?,entry_liquidity_usd=?,entry_volume_h1_usd=?,entry_buys_h1=?,entry_sells_h1=?,validation_reason=NULL WHERE id=?`,args:[now,now,p.price,p.liquidityUsd!,p.volumeH1Usd,p.buysH1,p.sellsH1,row.id]});await c.execute({sql:`INSERT OR IGNORE INTO solana_validated_snapshots(case_id,stage,captured_at,price,liquidity_usd) VALUES(?, 'INITIAL', ?, ?, ?)`,args:[row.id,now,p.price,p.liquidityUsd]});activated++;}return{activated,invalidDeleted,validationDue:due.length};}

async function writeSnapshots(c:Client,row:CaseRow,p:Pool,now:number){const age=(now-row.firstSeenAt)/60000;for(const[stage,due]of STAGES){if(age<due)continue;await c.execute({sql:`INSERT OR IGNORE INTO solana_validated_snapshots(case_id,stage,captured_at,price,liquidity_usd) VALUES(?,?,?,?,?)`,args:[row.id,stage,now,p.price,p.liquidityUsd]});}if(age>=60)await c.execute({sql:"UPDATE solana_validated_cases SET status='CLOSED' WHERE id=?",args:[row.id]});}
async function evaluateDueCase(c:Client,row:CaseRow){const ex=await c.execute({sql:"SELECT 1 FROM solana_validated_decisions WHERE case_id=?",args:[row.id]});if(ex.rows.length)return null;const r=await c.execute({sql:"SELECT * FROM solana_validated_snapshots WHERE case_id=? AND stage IN ('INITIAL','PLUS_5','PLUS_10')",args:[row.id]});const m=new Map(r.rows.map(s=>[String(s.stage),s]));const i=m.get("INITIAL"),p5=m.get("PLUS_5"),p10=m.get("PLUS_10");if(!i||!p5||!p10)return null;const d=evaluateRadar24({tokenCaseId:row.id,decisionStage:"PLUS_10",decidedAt:Number(p10.captured_at),radarVersion:RADAR_VERSION,entry:{entryPrice:row.entryPrice,entryValid:true},snapshots:{INITIAL:{stage:"INITIAL",capturedAt:Number(i.captured_at),price:Number(i.price),marketCap:null,liquidityUsd:asNumber(i.liquidity_usd)},PLUS_5:{stage:"PLUS_5",capturedAt:Number(p5.captured_at),price:Number(p5.price),marketCap:null,liquidityUsd:asNumber(p5.liquidity_usd)},PLUS_10:{stage:"PLUS_10",capturedAt:Number(p10.captured_at),price:Number(p10.price),marketCap:null,liquidityUsd:asNumber(p10.liquidity_usd)}}});let status=d.decisionStatus;let rejectReason:string|null=d.rejectReason;let executionStatus:string|null=null;let loss:number|null=null;if(status==="PASS"){const e=await validateJupiterExecution(row.mint);executionStatus=e.status;loss=e.roundTripLossPct;if(e.status!=="EXECUTION_PASS"){status="REJECT";rejectReason=e.reason??"EXECUTION_FAIL";}else if(loss==null||loss>MAX_ROUND_TRIP_LOSS_PCT){status="REJECT";rejectReason="EXECUTION_FAIL_ROUND_TRIP_LOSS_GT_3PCT";}}
await c.execute({sql:`INSERT INTO solana_validated_decisions(case_id,decided_at,status,reject_reason,plus5_roi_pct,plus10_roi_pct,momentum_5_to_10_pct,plus10_liquidity_usd,execution_status,round_trip_loss_pct,radar_version) VALUES(?,?,?,?,?,?,?,?,?,?,?)`,args:[row.id,Number(p10.captured_at),status,rejectReason,d.plus5RoiPct,d.plus10RoiPct,d.momentum5To10Pct,asNumber(p10.liquidity_usd),executionStatus,loss,RADAR_VERSION]});if(status!=="PASS")return{status,pushed:false};const claim=await c.execute({sql:"INSERT OR IGNORE INTO solana_validated_push_deliveries(case_id,sent_at) VALUES(?,?)",args:[row.id,Date.now()]});if(!claim.rowsAffected)return{status,pushed:false};const send=createWebPushSender({getSubscriptions:()=>getPushSubscriptions(c)});const payload:PushPayload={title:"🚀 Solana Radar · Validated",body:`${row.symbol??"SOL token"} | +10 ${d.plus10RoiPct?.toFixed(1)??"?"}% | RT loss ${loss?.toFixed(2)??"?"}%`,url:`/solana-cases/${row.id}`,mint:row.mint,decisionId:row.id,tokenCaseId:row.id,decisionStatus:"PASS",decisionStage:"PLUS_10",plus10RoiPct:d.plus10RoiPct,momentum5To10Pct:d.momentum5To10Pct,symbol:row.symbol};await send(payload);return{status,pushed:true};}

export async function runSolanaValidatedRadar(){const c=await createTursoClient();const now=Date.now();const errors:RunError[]=[];let rateLimited=false;try{await ensureSchema(c);const cleanup=await cleanupDatabase(c,now);let validation={activated:0,invalidDeleted:0,validationDue:0};try{validation=await validateWaiting(c,now);}catch(e){if(e instanceof GeckoRateLimitError){rateLimited=true;errors.push({caseId:null,message:e.message});}else throw e;}
let decisions=0,passes=0,pushes=0;if(!rateLimited){const active=await listActive(c);if(active.length){await sleep(GECKO_REQUEST_GAP_MS);try{const pools=await fetchPools(active.map(r=>r.poolAddress));for(const row of active){const p=pools.get(row.poolAddress.toLowerCase());if(!p)continue;await writeSnapshots(c,row,p,now);const out=await evaluateDueCase(c,row);if(out){decisions++;if(out.status==="PASS")passes++;if(out.pushed)pushes++;}}}catch(e){if(e instanceof GeckoRateLimitError){rateLimited=true;errors.push({caseId:null,message:e.message});}else throw e;}}}
let collection={discovered:0,waitingAdded:0};if(!rateLimited){await sleep(GECKO_REQUEST_GAP_MS);try{collection=await collectWaiting(c,now);}catch(e){if(e instanceof GeckoRateLimitError){rateLimited=true;errors.push({caseId:null,message:e.message});}else throw e;}}
const counts=await c.execute("SELECT COUNT(*) cases,SUM(CASE WHEN status='WAITING' THEN 1 ELSE 0 END) waiting,SUM(CASE WHEN status='ACTIVE' THEN 1 ELSE 0 END) active FROM solana_validated_cases");const summary={mode:"SOLANA_POST_VALIDATION",provider:{name:"GeckoTerminal",rateLimited},limits:{newPerRun:MAX_NEW_CANDIDATES_PER_RUN,duePerRun:MAX_DUE_VALIDATIONS_PER_RUN,activePerRun:MAX_ACTIVE_PER_RUN,maxDueBacklog:MAX_DUE_BACKLOG},validation:{minAgeMinutes:15,maxAgeMinutes:60,minEntryLiquidityUsd:MIN_ENTRY_LIQUIDITY_USD},decision:{plus10RoiMinPct:25,momentum5To10MinPct:0,jupiterRoundTripRequired:true,maxRoundTripLossPct:MAX_ROUND_TRIP_LOSS_PCT},cleanup,...validation,...collection,decisionsCreated:decisions,passesCreated:passes,pushesSent:pushes,totals:{cases:Number(counts.rows[0]?.cases??0),waiting:Number(counts.rows[0]?.waiting??0),active:Number(counts.rows[0]?.active??0)},errors};console.info("[solana-validated] cron finished",summary);return summary;}finally{c.close();}}
export async function handleSolanaValidatedCron(request:Request){const secret=process.env.CRON_SECRET;if(!secret||request.headers.get("authorization")!==`Bearer ${secret}`)return Response.json({ok:false,error:"Unauthorized"},{status:401});try{return Response.json({ok:true,...await runSolanaValidatedRadar()});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:String(e)},{status:500});}}
